api:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    prefix: /api
    name_prefix: api.
    trailing_slash_on_root: true
    type: attribute
    defaults:
        _format: json

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#kernel:
#  resource: ../src/Kernel.php
#  type: attribute
